# RANDOMUSER
RandomUser; geliştiricilere, test amacıyla yer tutucu (placeholder) olarak kullanılabilecek rastgele oluşturulmuş kullanıcı verileri sağlayan, açık kaynaklı ve ücretsiz bir API'dir. Bu araç, metin yerine insanlar için yer tutucu görevi görmesi bakımından Lorem Ipsum'a benzer. API birden fazla sonuç döndürebildiği gibi; cinsiyet, e-posta, görsel, kullanıcı adı, adres, unvan, ad, soyad ve daha fazlası gibi oluşturulan kullanıcı detaylarını da belirtebilir.

## Get Method'u Parametrelerinin birkaçı

In [3]:
""" 
            get_cell()
            get_city()
            get_dob()
            get_email()
            get_first_name()
            get_full_name()
            get_gender()
            get_id()
            get_id_number()
            get_id_type()
            get_info()
            get_last_name()
            get_login_md5()
            get_login_salt()
            get_login_sha1()
            get_login_sha256()
            get_nat()
            get_password()
            get_phone()
            get_picture()
            get_postcode()
            get_registered()
            get_state()
            get_street()
            get_username()
            get_zipcode()
"""

' \n            get_cell()\n            get_city()\n            get_dob()\n            get_email()\n            get_first_name()\n            get_full_name()\n            get_gender()\n            get_id()\n            get_id_number()\n            get_id_type()\n            get_info()\n            get_last_name()\n            get_login_md5()\n            get_login_salt()\n            get_login_sha1()\n            get_login_sha256()\n            get_nat()\n            get_password()\n            get_phone()\n            get_picture()\n            get_postcode()\n            get_registered()\n            get_state()\n            get_street()\n            get_username()\n            get_zipcode()\n'

In [6]:
from randomuser import RandomUser
import pandas as pd

In [17]:
r = RandomUser()
some_list = r.generate_users(10)                ## 10 tane rastgele kişi oluşturdu
print(some_list)

name = r.get_full_name()                        ## Tam isimleri getirir bu method
print(name)

for user in some_list:                                          ## bütün hepsini gezip tam adı karşısında emailini getir
    print(user.get_full_name(), " ", user.get_email())

[<randomuser.RandomUser object at 0x141866490>, <randomuser.RandomUser object at 0x141867b10>, <randomuser.RandomUser object at 0x141867ed0>, <randomuser.RandomUser object at 0x141af42d0>, <randomuser.RandomUser object at 0x141af4690>, <randomuser.RandomUser object at 0x141af5310>, <randomuser.RandomUser object at 0x141af4410>, <randomuser.RandomUser object at 0x141af4550>, <randomuser.RandomUser object at 0x141af4050>, <randomuser.RandomUser object at 0x141af4190>]
Anne-Jet Dammers
Angela Cox   angela.cox@example.com
Jasmin Zacharias   jasmin.zacharias@example.com
Toivo Valli   toivo.valli@example.com
Betty Schimmelpfennig   betty.schimmelpfennig@example.com
Samantha Welch   samantha.welch@example.com
Nenad Michel   nenad.michel@example.com
Celso Barbosa   celso.barbosa@example.com
Christian Mortensen   christian.mortensen@example.com
Sanni Kumpula   sanni.kumpula@example.com
Bruce Watson   bruce.watson@example.com

## Exercise 2

In [20]:
# rastgele 10 kullanıcının fotoğraflarını oluşturun.

for pictures in some_list:
    print(pictures.get_full_name()," ", pictures.get_picture())

Angela Cox   https://randomuser.me/api/portraits/women/23.jpg
Jasmin Zacharias   https://randomuser.me/api/portraits/women/83.jpg
Toivo Valli   https://randomuser.me/api/portraits/men/35.jpg
Betty Schimmelpfennig   https://randomuser.me/api/portraits/women/17.jpg
Samantha Welch   https://randomuser.me/api/portraits/women/61.jpg
Nenad Michel   https://randomuser.me/api/portraits/men/31.jpg
Celso Barbosa   https://randomuser.me/api/portraits/men/68.jpg
Christian Mortensen   https://randomuser.me/api/portraits/men/8.jpg
Sanni Kumpula   https://randomuser.me/api/portraits/women/41.jpg
Bruce Watson   https://randomuser.me/api/portraits/men/20.jpg

## Exercise 3

In [26]:
## Kullanıcılarla ilgili bilgileri içeren bir tablo oluşturmak için, istenen 
#  tüm parametreleri kapsayan bir fonksiyon yazabiliriz; örneğin isim, cinsiyet, şehir vb.

#"Get" metotlarını çağırır ve ardından kullanıcıları içeren bir pandas DataFrame'i döndürür.

from psutil import users


def get_users():
    users =[]

    for user in RandomUser.generate_users(10):
        users.append({"name": user.get_full_name(), "Gender": user.get_gender(), "City": user.get_city,
                      "State": user.get_state(), "Email": user.get_email(), "Dob":user.get_dob(), "Picture": user.get_picture() })

    return pd.DataFrame(users)

In [25]:
get_users()

,name,Gender,City,State,Email,Dob,Picture
0,Frederik Johansen,male,<bound method RandomUser.get_city of <randomus...,Syddanmark,frederik.johansen@example.com,1958-08-15T14:57:44.600Z,https://randomuser.me/api/portraits/men/28.jpg
1,Guy Wells,male,<bound method RandomUser.get_city of <randomus...,Northern Territory,guy.wells@example.com,1989-11-15T21:07:26.268Z,https://randomuser.me/api/portraits/men/88.jpg
2,Logan Wells,male,<bound method RandomUser.get_city of <randomus...,Wicklow,logan.wells@example.com,1977-05-30T02:08:21.692Z,https://randomuser.me/api/portraits/men/98.jpg
3,Iman Aase,female,<bound method RandomUser.get_city of <randomus...,Aust-Agder,iman.aase@example.com,1983-09-27T05:52:22.079Z,https://randomuser.me/api/portraits/women/68.jpg
4,Robbie Van der Weide,male,<bound method RandomUser.get_city of <randomus...,Limburg,robbie.vanderweide@example.com,1993-08-12T08:30:04.667Z,https://randomuser.me/api/portraits/men/44.jpg
5,علی رضا گلشن,male,<bound method RandomUser.get_city of <randomus...,زنجان,aalyrd.glshn@example.com,1983-10-16T04:30:19.239Z,https://randomuser.me/api/portraits/men/83.jpg
6,Daniela With,female,<bound method RandomUser.get_city of <randomus...,Oslo,daniela.with@example.com,1992-10-09T04:55:55.279Z,https://randomuser.me/api/portraits/women/58.jpg
7,Sören Boxem,male,<bound method RandomUser.get_city of <randomus...,Noord-Brabant,soren.boxem@example.com,1973-09-10T10:27:50.710Z,https://randomuser.me/api/portraits/men/24.jpg
8,Karl-Peter Stork,male,<bound method RandomUser.get_city of <randomus...,Rheinland-Pfalz,karl-peter.stork@example.com,1957-02-08T18:07:47.163Z,https://randomuser.me/api/portraits/men/61.jpg
9,William Ellis,male,<bound method RandomUser.get_city of <randomus...,Kilkenny,william.ellis@example.com,1950-04-10T13:55:55.727Z,https://randomuser.me/api/portraits/men/58.jpg

In [27]:
df1 = pd.DataFrame(get_users())

## Excersize 3 (Fruityvice API)

In [28]:
import requests
import json

In [ ]:
data = requests.get("https://web.archive.org/web/20240929211114/https://fruityvice.com/api/fruit/all", timeout=30)      ## 30 saniye sürsün alma
data.raise_for_status()

# Sonuçları `json.loads()` fonksiyonunu kullanarak alacağız.
result = json.loads(data.text)

## burayı bir datafram'e dönüştür
df = pd.DataFrame(result)
df.head()

,name,id,family,order,genus,nutritions
0,Persimmon,52,Ebenaceae,Rosales,Diospyros,"{'calories': 81, 'fat': 0.0, 'sugar': 18.0, 'c..."
1,Strawberry,3,Rosaceae,Rosales,Fragaria,"{'calories': 29, 'fat': 0.4, 'sugar': 5.4, 'ca..."
2,Banana,1,Musaceae,Zingiberales,Musa,"{'calories': 96, 'fat': 0.2, 'sugar': 17.2, 'c..."
3,Tomato,5,Solanaceae,Solanales,Solanum,"{'calories': 74, 'fat': 0.2, 'sugar': 2.6, 'ca..."
4,Pear,4,Rosaceae,Rosales,Pyrus,"{'calories': 57, 'fat': 0.1, 'sugar': 10.0, 'c..."

In [45]:
# kirazın familyasını ve cinsini bilmemiz gerekiyor.
cherry = df.loc[df["name"] == "Cherry"]
print(cherry.iloc[0]["family"]) 
print(cherry.iloc[0]["genus"])

Rosaceae
Prunus

In [62]:
## bir muzun kaç kalori içerdiğini öğrenin.
banana_calories = df.loc[df["name"] == "Banana", "nutritions"].iloc[0]["calories"]
print(banana_calories)

96

## Excersize 4

In [63]:
## 10 tane rastgele üretilmiş şaka için link var elimizde bunu içeri alalım

url = "https://official-joke-api.appspot.com/jokes/ten"
r = requests.get(url)

In [79]:
## bunu json formatında okuyalaım ve sonra bi dataframe dönüşyürelim
result = json.loads(r.text) 
df = pd.DataFrame(result)
df

,type,setup,punchline,id
0,programming,How do you check if a webpage is HTML5?,Try it out on Internet Explorer,55
1,programming,Why was the designer always cold?,Because they always used too much ice-olation.,445
2,general,What’s Forest Gump’s Facebook password?,1forest1,277
3,programming,To understand what recursion is...,You must first understand what recursion is,27
4,general,What do you call a cow on a trampoline?,A milk shake!,195
5,general,Did you hear about the runner who was criticized?,He just took it in stride,93
6,general,Why did the A go to the bathroom and come out ...,Because he had a vowel movement.,314
7,programming,I was gonna tell you a joke about UDP...,...but you might not get it.,71
8,general,Did you hear about the submarine industry?,It really took a dive...,95
9,general,How many optometrists does it take to change a...,1 or 2? 1... or 2?,141

In [80]:
## burada type ve id kolonlarını dropla
df = df.drop(columns=["type", "id"])

In [81]:
df

,setup,punchline
0,How do you check if a webpage is HTML5?,Try it out on Internet Explorer
1,Why was the designer always cold?,Because they always used too much ice-olation.
2,What’s Forest Gump’s Facebook password?,1forest1
3,To understand what recursion is...,You must first understand what recursion is
4,What do you call a cow on a trampoline?,A milk shake!
5,Did you hear about the runner who was criticized?,He just took it in stride
6,Why did the A go to the bathroom and come out ...,Because he had a vowel movement.
7,I was gonna tell you a joke about UDP...,...but you might not get it.
8,Did you hear about the submarine industry?,It really took a dive...
9,How many optometrists does it take to change a...,1 or 2? 1... or 2?