In [7]:
import pandas as pd
import numpy as np
import requests

###  Dünyanın en büyük bankalarının listesi(Wikipedia)

In [ ]:
import pandas as pd

url = "https://en.wikipedia.org/wiki/List_of_largest_banks"
# Wikipedia bot korumasını aşmak için user-agent tanımlıyoruz
df = pd.read_html(url, storage_options={"User-Agent": "Mozilla/5.0"})[0]
df

,Rank,Bank name,Total assets (April 2026) (US$ billion)
0,1,Industrial and Commercial Bank of China,7645.80
1,2,Agricultural Bank of China,6974.82
2,3,China Construction Bank,6524.05
3,4,Bank of China,5484.11
4,5,JPMorgan Chase,4424.90
...,...,...,...
95,96,Caixa Econômica Federal,403.70
96,97,SEB Group,398.24
97,98,Nomura Holdings,395.02
98,99,First Abu Dhabi Bank,382.19
99,100,QNB Group,381.61

### GSYİH'ye göre ülkelerin listesi

In [27]:
from webbrowser import Mozilla

import pandas as pd
import requests
from requests_toolbelt import user_agent

url = "https://en.wikipedia.org/wiki/List_of_countries_by_GDP_(nominal)"

table = pd.read_html(url, storage_options={"User-Agent": "Mozilla/5.0"})[2]
df = pd.DataFrame(table)
df


## ama unutma köprü metinleri de var bağlantılı olanlar n1 vs. onlar da çıkar

,Country/Territory,IMF (2026)[1],World Bank (2025)[6],United Nations (2024)[7]
0,World,126295331,118350166,111565144
1,United States,32383920,30769700,29298000
2,China[n 1],20851593,19498039,18743802
3,Germany,5452858,5050923,4659929
4,Japan,4379253,4435163,4026211
...,...,...,...,...
217,Palau,377,345,310
218,Marshall Islands,342,308,281
219,Nauru,196,176,187
220,Montserrat,—N/a,—N/a,81
221,Tuvalu,65,57,56