In [1]:
import requests
import pandas as pd
import numpy as np
from bs4 import BeautifulSoup

In [2]:
from IPython.core.display import HTML

html_code = """
<!DOCTYPE html>
<html>
<head>
<title> Page Title </title>
</head>
<body>
<h3><b id="boldest"> Lebron James </b></h3>
<p> Salary : $ 92,000,000 </p>
<h3> Stephen Curry </h3>
<p>Salary : $ 85,000,000</p>
<h3> Kevin Durant </h3>
<p>Salary : $ 73,200,000</p>
</body>
</html>
"""
HTML(html_code)

In [3]:
soup = BeautifulSoup(html_code, "html5lib")
print("1 : ",soup.title)            # 1
print("2 : ",soup.h3)           # 2
print("3 : ",soup.b)            # 3

tag_child = soup.b
print("4 :", tag_child)         # 4

parent_tag = tag_child.parent
print("5 :",parent_tag)         #5

sibling_1 = parent_tag.find_next_sibling()
print("6 :", sibling_1)         #6

print("7: " ,tag_child.attrs)   # 7 öznitelik adı ve değeri sözlük olarak
print("8 :", tag_child.string)  # 8 içeriği de gezebilirsin string ifadesi için

1 :  <title> Page Title </title>
2 :  <h3><b id="boldest"> Lebron James </b></h3>
3 :  <b id="boldest"> Lebron James </b>
4 : <b id="boldest"> Lebron James </b>
5 : <h3><b id="boldest"> Lebron James </b></h3>
6 : <p> Salary : $ 92,000,000 </p>
7:  {'id': 'boldest'}
8 :  Lebron James

In [4]:
html_content ="""
<table>
  <tr>
    <td>Pizza Place</td>
    <td>Orders</td>
    <td>Slices</td>
  </tr>
  <tr>
    <td>Domino's Pizza</td>
    <td>10</td>
    <td>100</td>
  </tr>
  <tr>
    <td>Little Caesars</td>
    <td>12</td>
    <td>144</td>
  </tr>
</table>
"""

In [5]:
table = BeautifulSoup(html_content, "html5lib")

table_row = table.find_all(name= "tr")          ## tr sütununu verdi
print("1- Bütün kolon isimleri: \n",table_row)

print("****************")

first_row = table_row[0]                        ## ilk sütunumuzu çekebiliriz tablodaki
print("2- Tablodaki ilk row: \n", first_row)

print("****************")

first_row_cell = first_row.td
print("3-İlk tablonun ilk hücresi: ", first_row_cell)

print("*****************")

for i,row in enumerate(table_row):
    print("row", i)
    cells = row.find_all("td")                  ## iç içe geçmiş bir for döngüsü ile tabloyu tek tek açıklayıcı dönelim

    for j,cell in enumerate(cells):
        print("column", j, "cell", cell)

1- Bütün kolon isimleri:
 [<tr>
    <td>Pizza Place</td>
    <td>Orders</td>
    <td>Slices</td>
  </tr>, <tr>
    <td>Domino's Pizza</td>
    <td>10</td>
    <td>100</td>
  </tr>, <tr>
    <td>Little Caesars</td>
    <td>12</td>
    <td>144</td>
  </tr>]
****************
2- Tablodaki ilk row:
 <tr>
    <td>Pizza Place</td>
    <td>Orders</td>
    <td>Slices</td>
  </tr>
****************
3-İlk tablonun ilk hücresi:  <td>Pizza Place</td>
*****************
row 0
column 0 cell <td>Pizza Place</td>
column 1 cell <td>Orders</td>
column 2 cell <td>Slices</td>
row 1
column 0 cell <td>Domino's Pizza</td>
column 1 cell <td>10</td>
column 2 cell <td>100</td>
row 2
column 0 cell <td>Little Caesars</td>
column 1 cell <td>12</td>
column 2 cell <td>144</td>

## Eski örnek tekrarı (Wikipedia en değerli bankalar)

In [6]:
url = "https://en.wikipedia.org/wiki/List_of_largest_banks"

df = pd.read_html(url, storage_options={"User-Agent": "Mozilla/5.0"})[0]
df.head()

,Rank,Bank name,Total assets (April 2026) (US$ billion)
0,1,Industrial and Commercial Bank of China,7645.80
1,2,Agricultural Bank of China,6974.82
2,3,China Construction Bank,6524.05
3,4,Bank of China,5484.11
4,5,JPMorgan Chase,4424.90

In [7]:
url_country = "https://en.wikipedia.org/wiki/List_of_countries_by_GDP_(nominal)"

df1= pd.read_html(url_country, storage_options={"User-Agent": "Mozilla/5.0"})[2]
df1

,Country/Territory,IMF (2026)[1],World Bank (2025)[6],United Nations (2024)[7]
0,World,126295331,118350166,111565144
1,United States,32383920,30769700,29298000
2,China[n 1],20851593,19498039,18743802
3,Germany,5452858,5050923,4659929
4,Japan,4379253,4435163,4026211
...,...,...,...,...
217,Palau,377,345,310
218,Marshall Islands,342,308,281
219,Nauru,196,176,187
220,Montserrat,—N/a,—N/a,81
221,Tuvalu,65,57,56